# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      STACK_NAME: ${{ secrets.STACK_NAME }}
      REGION: ${{ secrets.REGION }}
      BUCKET: ${{ secrets.BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v1
      - run: sam build 
      - run: sam deploy --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --region $REGION --s3-bucket $BUCKET
